### ISSUE TITLE
set up ghactions -> push to gitlab

### ISSUE THREAD

**Issue by mpadge** [mpadge/pkgreport#1]
ping @RobJY

**Comment by mpadge** [comment]
Yo @RobJY, it's all worked out via [this yaml script](https://github.com/mpadge/pkgreport/blob/master/.github/workflows/gitlab.yaml), copied here for self-contained reference. Every push to github then triggers the action to push same to gitlab.

``` yaml
name: gitlab

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    #if: "!(contains(github.event.head_commit.message, 'nogl'))"

    steps:
    - uses: actions/checkout@v2

    - name: Git setup
      run: |
          sudo git config --global user.name ${{secrets.UNAME}}
          sudo git config --global user.email ${{secrets.EMAIL}}
          sudo git clone https://${{secrets.UNAME}}:${{secrets.GH_TOKEN}}@github.com/mpadge/pkgreport
          sudo git fetch --unshallow origin
          sudo git remote add gitlab https://${{secrets.UNAME}}:${{secrets.GLPW}}@gitlab.com/mpadge/pkgreport.git
          sudo git push --force gitlab master

```

Some notes:

1. Lots of variables used all of which are stored in the **github** repo settings. There are no secrets in the gitlab version
2. The `GLPW` secret is the password for gitlab
3. `sudo git` is always necessary, as is the `unshallow` fetch, and the `--force` on `push`. There might be better ways around this, but it works for now.
4. **Important** You need to unprotect the `master` (or whatever) branch of gitlab via Settings -> Repository -> Protected Branches -> Unprotect master branch
5. The commented-out line will allow push to gitlab to be skipped if commit message contains `"nogl"` (or replace with whatever).

Equivalent ways to push via SSH rather than https would follow fairly naturally by extension.
